---
title: "Cohort-level analysis"
format: html
---

{{< include _data.qmd >}}

```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(ComplexHeatmap)
library(circlize)
library(flextable)
```


```{r}
columns_to_count <- c("Stage", "Grade", "Histotype", "LVI", "Nodes", "Myo", "Chemotherapy", "Radiotherapy", "Brachytherapy")

capitalize_names <- function(x) {
  str_to_sentence(x) %>% str_replace_all("mmmt", "MMMT")
}

palette_histotype_capitalized <- palette_histotype
names(palette_histotype_capitalized) <- capitalize_names(names(palette_histotype_capitalized))

palette_myo_capitalized <- palette_myo
names(palette_myo_capitalized) <- capitalize_names(names(palette_myo_capitalized))

palette_grade_missing <- c(palette_grade, "Missing"="#FFFFFF")
palette_lvi_missing <- c(palette_lvi, "Missing"="#FFFFFF")
palette_nodes_missing <- c(palette_nodes, "Missing"="#FFFFFF")
palette_myo_missing <- c(palette_myo_capitalized, "Missing"="#FFFFFF")
palette_stage_missing <- c(palette_stage, "Missing"="#FFFFFF")

metatable_full_unique <- metatable_full %>%
  dplyr::select(-c(TMA, `B & T`, `Adaptive Resistance`, Cohort)) %>%
  dplyr::mutate(across(c("Grade", "Histotype", "LVI", "Nodes", "Myo", "Chemotherapy", "Brachytherapy", "Stage"), ~replace_na(as.character(.x), "Missing"))) %>%
  dplyr::mutate(Histotype = capitalize_names(Histotype),
                Myo = capitalize_names(Myo)) %>%
  dplyr::mutate(
    Histotype = factor(Histotype, levels = intersect(names(palette_histotype_capitalized), unique(Histotype))),
    Grade = factor(Grade, levels = names(palette_grade_missing)),
    LVI = factor(LVI, levels = names(palette_lvi_missing)),
    Nodes = factor(Nodes, levels = names(palette_nodes_missing)),
    Myo = factor(Myo, levels = names(palette_myo_missing)),
    Chemotherapy = factor(Chemotherapy, levels = names(palette_binary)),
    Radiotherapy = factor(Radiotherapy, levels = names(palette_binary)),
    Brachytherapy = factor(Brachytherapy, levels = names(palette_binary)),
    Stage = factor(Stage, levels = names(palette_stage_missing))
  ) %>%
  unique

renamed_columns <- lapply(columns_to_count, function(x) {
  count_t <- table(metatable_full_unique[,x])
  count_n <- names(count_t)
  count_v <- unname(count_t)
  
  list(labels = paste0(paste(count_n, count_v, sep = " (n="), ")"))
})
names(renamed_columns) <- columns_to_count

renamed_columns$Age <- list(direction = "horizontal")
renamed_columns$Stage <- c(renamed_columns$Stage, nrow = 2)
renamed_columns$Grade <- c(renamed_columns$Grade, nrow = 2)
renamed_columns$Nodes <- c(renamed_columns$Nodes, nrow = 2)
renamed_columns$Myo <- c(renamed_columns$Myo, nrow = 2)
renamed_columns$LVI <- c(renamed_columns$LVI, nrow = 2)
renamed_columns$Chemotherapy <- c(renamed_columns$Chemotherapy, nrow = 1)
renamed_columns$Radiotherapy <- c(renamed_columns$Radiotherapy, nrow = 1)
renamed_columns$Brachytherapy <- c(renamed_columns$Brachytherapy, nrow = 1)

cohort_df_unique <- metatable_full_unique %>% dplyr::select(-c(acc_num, Neoadjuvant, Subtype)) %>% as.data.frame

cohort_plot_bottom <- rowAnnotation(df = cohort_df_unique, 
                                       col = list(
                                         #Cohort=palette_cohort,
                                         Age=colorRamp2(c(min(metatable_full$Age, na.rm = TRUE),  max(metatable_full$Age, na.rm = TRUE)), c("lightgray", "#2E294E")),
                                         Grade=palette_grade_missing,
                                         Histotype=palette_histotype_capitalized,
                                         LVI=palette_lvi_missing,
                                         Nodes=palette_nodes_missing,
                                         Myo=palette_myo_missing,
                                         #Neoadjuvant=palette_neoadjuvant,
                                         Chemotherapy=palette_binary,
                                         Radiotherapy=palette_binary,
                                         Brachytherapy=palette_binary,
                                         Stage=palette_stage_missing
                                       ), 
                                       na_col = "white",
                                       annotation_legend_param = renamed_columns,
                                    annotation_name_rot = 45
)

cohort_plot_top <- columnAnnotation(df = cohort_df_unique, 
                                    col = list(
                                      #TMA=palette_tma,
                                      `B & T`=palette_binary,
                                      #Angiogenesis=palette_binary,
                                      `Adaptive Resistance`=palette_binary
                                    ))
```

```{r, fig.width = 10, fig.height = 8, fig.align = 'center'}
#| label: fig-cohort-track
#| fig-cap: "Cohort overview"
#| fig-alt: "Cohort overview. Find out what's going on with angiogenesis."
cohort_track <- Heatmap(matrix(nr = nrow(metatable_full_unique %>% dplyr::select(-c(acc_num, Neoadjuvant, Subtype)) %>% as.data.frame), nc = 0), 
	#top_annotation = cohort_plot_top, bottom_annotation = cohort_plot_bottom)
	left_annotation = cohort_plot_bottom)

draw(cohort_track, annotation_legend_side = "bottom")
```

```{r, fig.width = 6, fig.height = 24}
#| label: suppfig-count-distributions
count_distributions <- counts_summarized %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "black") +
  scale_x_continuous(trans = 'log1p', breaks = c(0, 1, 10, 100, 1000, 10000),
                     labels = c("0", "1", "10", "100", "1000", "10000")) + 
  facet_grid(variable ~ region, scales = "free") +
  labs(title = "Variables") + 
  theme_pubr() + 
  ggtitle("Counts")

count_distributions
```

```{r}
#| label: tbl-cohort-overview
#| tbl-cap: "Cohort statistics"
summarizor(metatable_full %>% 
             dplyr::select(Histotype, Age, Stage, Myo, Nodes, LVI, Chemotherapy, Radiotherapy, Brachytherapy, acc_num) %>% 
             unique %>% 
             dplyr::select(-c(acc_num)) %>% 
             dplyr::mutate(Histotype = factor(Histotype, levels = c(names(metatable_full$Histotype %>% table %>% sort %>% rev)))) %>%
             dplyr::rename(Myoinvasion=Myo, `Lymph node status` = Nodes, `Lymphovascular invasion`=LVI)) %>% flextable::as_flextable() %>% autofit()
```