---
title: "Mutational signatures"
format: html
---

{{< include _data.qmd >}}

```{r, warning=FALSE, include=FALSE}
library(tidyverse)
library(here)
library(ggpubr)
library(ggforce)
library(cowplot)
library(ComplexHeatmap)

here::i_am("paper/notebooks/mutational_signatures.qmd")
```

```{r}
clinical_annotations_comb_tma <- metatable_clinical %>%
  select(acc_num, Grade, Histotype, Neoadjuvant, Subtype, Stage) %>%
  unique %>%
  left_join(clust_assignments_map)
```

```{r}
cnsig_merged <- cnsig_exposures %>% 
  inner_join(clinical_annotations_comb_tma)

cnsig_merged_long <- cnsig_merged %>% 
  pivot_longer(cols = colnames(cnsig_merged)[str_detect(colnames(cnsig_merged), "^(VS|BS)")],
               names_to = "signature", 
               values_to = "exposure") %>%
  unique %>%
  filter(!is.na(clust_map),
         str_detect(signature, "^VS"))

cnsig_pvals <- compare_means(exposure ~ clust_map, cnsig_merged_long, group.by = c("signature"), method = "wilcox.test", p.adjust.method = "holm") %>%
  dplyr::mutate(p.final = paste0("italic(P)==", p.adj))

cnsig_boxplots <- ggplot(cnsig_merged_long, aes(x=clust_map, y=exposure)) + 
  geom_boxplot(aes(fill=clust_map), alpha = 0.4, width = 0.5, outlier.size = -1) + 
  geom_point(position = position_jitter(width = 0.2, height = 0), alpha = 0.3) + 
  theme_pubr() + 
  scale_fill_manual(values = palette_tilclust) + 
  facet_wrap(~ signature, scales = "free_y", ncol = 5) +
  #stat_compare_means(vjust = 0.7, size = 3)# + 
  #stat_compare_means(comparisons = list(c("Low TIL", "High TIL"))) + 
  theme(strip.background =element_rect(fill="white")) +
  stat_pvalue_manual(data = cnsig_pvals, label = "p.final", y.position = 0.9, vjust=1.2, size = 3, remove.bracket = TRUE, parse = TRUE) + 
  xlab("") + 
  ylab("Exposure") + 
  labs(fill = "Cluster") + 
  guides(fill = guide_legend(override.aes = list(alpha = 1)))

cnsig_boxplots_no_vs5 <- ggplot(cnsig_merged_long %>% filter(signature != "VS5"), aes(x=clust_map, y=exposure)) + 
  geom_boxplot(aes(fill=clust_map), alpha = 0.4, width = 0.5, outlier.size = -1) + 
  geom_point(position = position_jitter(width = 0.2, height = 0), alpha = 0.3) + 
  theme_pubr() + 
  scale_fill_manual(values = palette_tilclust) + 
  facet_wrap(~ signature, scales = "free_y", ncol = 5) +
  #stat_compare_means(vjust = 0.7, size = 3)# + 
  #stat_compare_means(comparisons = list(c("Low TIL", "High TIL"))) + 
  theme(strip.background =element_rect(fill="white")) +
  stat_pvalue_manual(data = cnsig_pvals %>% filter(signature != "VS5"), label = "p.final", y.position = 0.9, vjust=1.2, size = 3, remove.bracket = TRUE, parse = TRUE) + 
  xlab("") + 
  ylab("Exposure") + 
  labs(fill = "Cluster") + 
  guides(fill = guide_legend(override.aes = list(alpha = 1)))

cnsig_vs5 <- ggplot(cnsig_merged_long %>% filter(signature == "VS5"), aes(x=clust_map, y=exposure)) +
  geom_boxplot(aes(fill=clust_map), alpha = 0.4, width = 0.5, outlier.size = -1) + 
  geom_point(position = position_jitter(width = 0.2, height = 0), alpha = 0.3) + 
  theme_pubr() + 
  scale_fill_manual(values = palette_tilclust) + 
  #stat_compare_means(vjust = 0.7, size = 3)# + 
  #stat_compare_means(comparisons = list(c("Low TIL", "High TIL"))) + 
  stat_pvalue_manual(data = cnsig_pvals %>% filter(signature == "VS5"), label = "p.final", y.position = 0.9, vjust=1.2, size = 3, remove.bracket = TRUE, parse = TRUE) + 
  xlab("") + 
  ylab("Exposure") + 
  labs(fill = "Cluster") + 
  guides(fill = guide_legend(override.aes = list(alpha = 1))) + 
  ggtitle("HRD CN signature") + 
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5))
```

```{r}
cnsig_wide <- cnsig_merged_long %>%
  filter(str_detect(signature, "^VS")) %>%
  pivot_wider(id_cols = c("acc_num", "clust_map"), names_from = "signature", values_from = "exposure")

cnsig_matrix <- cnsig_wide %>%
  select(-c(clust_map)) %>%
  column_to_rownames("acc_num")

clustmap_anno <- columnAnnotation(df = cnsig_wide %>% select(acc_num, clust_map) %>% rename(Cluster=clust_map) %>% column_to_rownames("acc_num"), annotation_width = 0.02, 
                                  col = list(
                                    Cluster=palette_tilclust
                                  ), show_legend = c(FALSE))

cnsig_heatmap <- Heatmap(cnsig_matrix %>% t,
                         na_col = "gray",
                         column_names_gp = gpar(fontsize = 6), 
                         cluster_rows = FALSE,
                         cluster_columns = TRUE,
                         clustering_method_columns = "ward.D2",
                         clustering_method_rows = "ward.D2",
                         clustering_distance_columns = "pearson",
                         column_names_rot = 60, 
                         show_column_names = FALSE,
                         top_annotation = clustmap_anno,
                         heatmap_legend_param = list(
                           title = "Exposure"
                         ))

cnsig_heatmap_plot <- grid::grid.grabExpr(draw(cnsig_heatmap, heatmap_legend_side = "right", annotation_legend_side="bottom"))
```

```{r}
her2_ihc_plot <- ggplot(her2_ihc_clust_assignments %>% filter(!is.na(her2_ihc)), aes(x=her2_ihc, fill = clust_map)) + 
  geom_bar(width = 0.5) + 
  xlab("HER2 (IHC)") + 
  theme_pubr() + 
  guides(fill = FALSE) +
  scale_fill_manual(values = palette_tilclust) + 
  ylab("Samples")

her2_swgs_plot <- ggplot(her2_ihc_clust_assignments %>% 
                           filter(sWGS != "No Data") %>%
                           mutate(sWGS = factor(sWGS, levels = c("Normal", "Loss", "Gain", "Amplification", "High Amplification")) %>% factor(labels = c("Normal", "Loss", "Gain", "Amp", "HLAmp"))), aes(x=sWGS, fill = clust_map)) + 
  geom_bar(width = 0.5) + 
  xlab("HER2 (CN)") + 
  theme_pubr() + 
  guides(fill = FALSE) +
  scale_fill_manual(values = palette_tilclust) + 
  ylab("Samples")
```

```{r}
## Overview plot by marker type
signature_summary <- cnsig_merged_long %>% 
  dplyr::select(c(patient_id, study_id, acc_num, max_van_sig)) %>% 
  unique %>% 
  dplyr::mutate(
    `HRD CN signature` = (max_van_sig == "VS5")
  )

her2_summary <- her2_ihc_clust_assignments %>% 
  dplyr::select(c(acc_num, clust_map, patient_id, study_id, her2_ihc, sWGS, ploidy)) %>%
  unique %>%
  dplyr::mutate(
    HER2=(sWGS %in% c("Amplification", "High Amplification")) | (her2_ihc == 3)
  )

biomarker_summary <- signature_summary %>% 
  dplyr::full_join(her2_summary) %>%
  dplyr::rename(TIL=clust_map) %>%
  dplyr::mutate(
    HER2=factor(dplyr::recode(as.character(HER2), 'FALSE'='Negative', 'TRUE'='Positive'), levels = c('Positive', 'Negative')),
    `HRD CN signature`=factor(dplyr::recode(as.character(`HRD CN signature`), 'FALSE'='Negative', 'TRUE'='Positive'), levels = c('Positive', 'Negative'))
  ) %>%
  dplyr::filter(!is.na(HER2), !is.na(`HRD CN signature`)) %>%
  dplyr::arrange(`HRD CN signature`, HER2, desc(TIL))

paste0("(", round(with(biomarker_summary, sum(as.numeric(HER2 == "Yes"), na.rm=TRUE)/sum(!is.na(HER2), na.rm=TRUE)), 2) * 100, "%)")

biomarker_labels_quantified <- c(
  "TIL",
  paste0("HRD CN signature ", "(", round(with(biomarker_summary, sum(as.numeric(`HRD CN signature` == "Positive"), na.rm=TRUE)/sum(!is.na(`HRD CN signature`), na.rm=TRUE)), 2) * 100, "%)"),
  paste0("HER2 ", "(", round(with(biomarker_summary, sum(as.numeric(HER2 == "Positive"), na.rm=TRUE)/sum(!is.na(HER2), na.rm=TRUE)), 2) * 100, "%)")
)

positive_palette <- palette_binary
names(positive_palette) <- c("Positive", "Negative")

biomarker_annotation <- columnAnnotation(df = biomarker_summary %>% dplyr::select(c(TIL, `HRD CN signature`, HER2)) %>% as.data.frame, 
                                       col = list(
                                         TIL=palette_tilclust,
                                         `HRD CN signature`=positive_palette,
                                         HER2=positive_palette
                                       ), 
                                       na_col = "white",
                                       show_legend = c(FALSE, TRUE, TRUE), 
                                       annotation_label = biomarker_labels_quantified,
                                       annotation_legend_param = lapply(biomarker_labels_quantified, function(x) {
                                         list(title = str_replace(x, " \\(.*", ""))
                                       })
)

biomarker_track <- Heatmap(matrix(nc = nrow(biomarker_summary), nr = 0), 
	bottom_annotation = biomarker_annotation)

biomarker_heatmap_plot <-grid::grid.grabExpr(draw(biomarker_track, heatmap_legend_side = "bottom", annotation_legend_side="bottom", legend_grouping = "original", merge_legend = TRUE, align_heatmap_legend = "heatmap_center"), width = 10, height = 8)
```

```{r, fig.width = 10, fig.height = 7}
#| label: fig-mutational-signatures
#| fig-cap: "Mutational signatures"
#| fig-alt: "Mutational signatures"

legend <- get_legend(cnsig_boxplots_no_vs5)

her2_row <- plot_grid(cnsig_vs5, her2_ihc_plot, her2_swgs_plot, ncol = 3, labels = c("b", "c", "d"), rel_widths = c(0.4, 0.45, 0.55))

plot_grid(legend, biomarker_heatmap_plot, her2_row, nrow = 3, labels = c("a", "", ""), rel_heights = c(0.1, 0.4, 0.6))
```

```{r, fig.width = 10, fig.height = 7}
## Supplemental Figure
plot_grid(legend, cnsig_heatmap_plot, cnsig_boxplots_no_vs5 + theme(legend.position = "none"), nrow = 3, labels = c("", "a", "b", ""), rel_heights = c(0.1, 0.6, 0.6))
```


```{r}
## TESTS

unique_outcomes <- c("os", "pfs", "dss")

clinical_clust_mutsig <- clinical_long_clust_assignments %>%
  inner_join(cnsig_wide %>% unique)

cox_fits_mutsig <- lapply(unique_outcomes, function(x) {
  df <- clinical_clust_mutsig %>% 
    filter(outcome == x) %>%
    rename(
      Age=age_dx,
      TIL=clust_map,
      Chemotherapy=chemo,
      Radiotherapy=rt,
      Brachytherapy=brachy,
      Stage=stage_main
    ) %>%
    mutate(
      TIL=factor(TIL, labels = c("TIL-poor", "TIL-rich"))
    )
  cox_fit <- coxph(Surv(time, status) ~  Age + TIL + Chemotherapy + Radiotherapy + Brachytherapy + Stage + VS1, data = df)
  
  return(cox_fit)
})
names(cox_fits_mutsig) <- unique_outcomes
```
