---
title: "Cohort-level analysis"
format: html
---

{{< include _data.qmd >}}

```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(ComplexHeatmap)
library(circlize)
library(flextable)
```


```{r}
capitalize_names <- function(x) {
  str_to_sentence(x) %>% str_replace_all("mmmt", "MMMT")
}

palette_histotype_capitalized <- palette_histotype
names(palette_histotype_capitalized) <- capitalize_names(names(palette_histotype_capitalized))

palette_myo_capitalized <- palette_myo
names(palette_myo_capitalized) <- capitalize_names(names(palette_myo_capitalized))

cohort_plot_bottom <- columnAnnotation(df = metatable_full %>% 
                                         dplyr::select(-c(acc_num, TMA, `B & T`, `Adaptive Resistance`, Neoadjuvant)) %>% 
                                         dplyr::mutate(Histotype = capitalize_names(Histotype),
                                                       Myo = capitalize_names(Myo)) %>%
                                         as.data.frame, 
                                       col = list(
                                         Cohort=palette_cohort,
                                         Age=colorRamp2(c(min(metatable_full$Age, na.rm = TRUE),  max(metatable_full$Age, na.rm = TRUE)), c("lightgray", "#2E294E")),
                                         Subtype=palette_subtype,
                                         Grade=palette_grade,
                                         Histotype=palette_histotype_capitalized,
                                         LVI=palette_lvi,
                                         Nodes=palette_nodes,
                                         Myo=palette_myo_capitalized,
                                         #Neoadjuvant=palette_neoadjuvant,
                                         Chemotherapy=palette_binary,
                                         Radiotherapy=palette_binary,
                                         Brachytherapy=palette_binary,
                                         Stage=palette_stage
                                       ), na_col = "white")

cohort_plot_top <- columnAnnotation(df = metatable_full %>% dplyr::select(c(TMA, `B & T`, `Adaptive Resistance`)) %>% as.data.frame, 
                                    col = list(
                                      TMA=palette_tma,
                                      `B & T`=palette_binary,
                                      #Angiogenesis=palette_binary,
                                      `Adaptive Resistance`=palette_binary
                                    ))
```

```{r, fig.width = 19, fig.height = 7, fig.align = 'center'}
#| label: fig-cohort-track
#| fig-cap: "Cohort overview"
#| fig-alt: "Cohort overview. Find out what's going on with angiogenesis."
cohort_track <- Heatmap(matrix(nc = nrow(metatable_full), nr = 0), 
	top_annotation = cohort_plot_top, bottom_annotation = cohort_plot_bottom)

draw(cohort_track, annotation_legend_side = "bottom")
```

```{r, fig.width = 6, fig.height = 24}
#| label: suppfig-count-distributions
count_distributions <- counts_summarized %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "lightblue", color = "black") +
  scale_x_continuous(trans = 'log1p', breaks = c(0, 1, 10, 100, 1000, 10000),
                     labels = c("0", "1", "10", "100", "1000", "10000")) + 
  facet_grid(variable ~ region, scales = "free") +
  labs(title = "Variables") + 
  theme_pubr() + 
  ggtitle("Counts")

count_distributions
```

```{r}
#| label: tbl-cohort-overview
#| tbl-cap: "Cohort statistics"
summarizor(metatable_full %>% 
             dplyr::select(Histotype, Age, Stage, Myo, Nodes, LVI, Chemotherapy, Radiotherapy, Brachytherapy, acc_num) %>% 
             unique %>% 
             dplyr::select(-c(acc_num)) %>% 
             dplyr::mutate(Histotype = factor(Histotype, levels = c(names(metatable_full$Histotype %>% table %>% sort %>% rev)))) %>%
             dplyr::rename(Myoinvasion=Myo, `Lymph node status` = Nodes, `Lymphovascular invasion`=LVI)) %>% flextable::as_flextable() %>% autofit()
```