project:
  type: manuscript

execute:
  freeze: auto

format:
  elsevier-html:
    cite-style: number
    toc: true
  elsevier-docx:
    cite-style: number
  elsevier-pdf:
    cite-style: number
      

crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false